# SPDX-License-Identifier: Apache-2.0
# Copyright 2024-2026 Dragonscale Industries Inc.
"""Type stubs for the ``uniko._uniko`` PyO3 extension.

Hand-written to mirror the native surface. Every facade verb has two skins:
the async method returns an awaitable driven by ``asyncio``; its ``*_sync``
twin blocks the calling thread and returns the resolved value directly.
"""

import datetime
from typing import Any, Awaitable

__version__: str

# ── Internal test helpers ─────────────────────────────────────────────────
# Exposed by the extension for the foundation test-suite; not part of the
# public API. Underscore-prefixed to signal "internal".

def _value_roundtrip(obj: Any) -> Any: ...
def _records_roundtrip(rows: list[dict[str, Any]]) -> list[dict[str, Any]]: ...
def _raise_error(kind: str) -> None: ...
def _now_utc() -> datetime.datetime: ...

# ── Exceptions ────────────────────────────────────────────────────────────

class UnikoError(Exception):
    """Base class for every binding error; carries a ``.kind`` discriminant."""

    kind: str

class ConfigError(UnikoError): ...
class LlmError(UnikoError): ...
class TimeoutError(UnikoError): ...
class ConflictError(UnikoError): ...
class UnsupportedError(UnikoError): ...

# ── Output value types (frozen snapshots) ─────────────────────────────────

class RecallSource:
    kind: str
    message_id: str | None
    artifact_id: str | None
    chunk_id: str | None
    def __repr__(self) -> str: ...

class RecallItem:
    node_id: int
    kind: str
    score: float
    content: str
    sources: list[RecallSource]
    def __repr__(self) -> str: ...

class ContextBundle:
    items: list[RecallItem]
    total_tokens: int
    phase1_only: bool
    phase2_only: bool
    coverage: float
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class Answer:
    text: str
    model: str | None
    input_tokens: int | None
    output_tokens: int | None
    recorded_episode: int | None
    context: ContextBundle
    def citations(self) -> list[RecallSource]: ...
    def __repr__(self) -> str: ...

class ObserveResult:
    message_node_id: int
    chunk_node_ids: list[int]
    session_node_id: int
    sender_node_id: int | None
    sender_id: str | None
    extracted_entities: list[tuple[int, str]]
    extracted_observations: list[int]
    attachment_count: int
    def __repr__(self) -> str: ...

class DeletionReport:
    nodes_deleted: int
    edges_deleted: int
    facts_invalidated: int
    chains_repaired: int
    nodes_redacted: int
    root_existed: bool
    def __repr__(self) -> str: ...

class FinalizeReport:
    transcript_chunks: list[int]
    observation_chunks: list[int]
    rebuilt: bool
    ended_at: datetime.datetime | None
    def __repr__(self) -> str: ...

class CycleStats:
    observations_processed: int
    facts_created: int
    facts_reinforced: int
    facts_invalidated: int
    drift_alerts: int
    def __repr__(self) -> str: ...

class MessageView:
    message_id: str
    sender_id: str
    content: str
    timestamp: datetime.datetime
    session_id: str
    addressed_to: list[str]
    attachments: list[str]
    def __repr__(self) -> str: ...

class ArtifactView:
    artifact_id: str
    kind: str
    mime: str | None
    path: str | None
    text: str
    attached_to_message: str | None
    def __repr__(self) -> str: ...

class GoalView:
    goal_id: str
    title: str
    description: str | None
    status: str
    phase: str
    created_at: datetime.datetime | None
    deadline: datetime.datetime | None
    completed_at: datetime.datetime | None
    metrics: Any | None
    def __repr__(self) -> str: ...

class TaskView:
    task_id: str
    title: str
    description: str | None
    status: str
    phase: str
    priority: float | None
    goal_id: str | None
    created_at: datetime.datetime | None
    completed_at: datetime.datetime | None
    def __repr__(self) -> str: ...

class GoalContext:
    goal: GoalView
    tasks: list[TaskView]
    sessions: list[str]
    recent_messages: list[str]
    facts: list[str]
    entities: list[str]
    def __repr__(self) -> str: ...

class IngestOutcome:
    kind: str
    artifact_id: str
    artifact_node_id: int
    chunk_node_ids: list[int]
    was_deduplicated: bool
    page_count: int | None
    extraction_failed: bool | None
    def __repr__(self) -> str: ...

class AbductionResult:
    modifications: list[dict[str, Any]]
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

# ── Input / value-object builders ─────────────────────────────────────────

class LlmSpec:
    @staticmethod
    def openai(alias: str, model_id: str, base_url: str | None = ...) -> LlmSpec: ...
    @staticmethod
    def openai_with_key_env(
        alias: str, model_id: str, key_env: str, base_url: str | None = ...
    ) -> LlmSpec: ...
    @staticmethod
    def mistralrs(alias: str, model_id: str) -> LlmSpec: ...
    def __repr__(self) -> str: ...

class IngestSource:
    @staticmethod
    def from_text(content: str) -> IngestSource: ...
    @staticmethod
    def from_bytes(data: bytes) -> IngestSource: ...
    @staticmethod
    def from_path(path: str) -> IngestSource: ...
    def with_mime(self, mime: str) -> IngestSource: ...
    def with_id(self, id: str) -> IngestSource: ...
    def with_path(self, path: str) -> IngestSource: ...
    def __repr__(self) -> str: ...

class Scope:
    def __init__(self) -> None: ...
    def sessions(self, sessions: list[str]) -> Scope: ...
    def participants(self, participants: list[str]) -> Scope: ...
    def since(self, since: datetime.datetime) -> Scope: ...
    def until(self, until: datetime.datetime) -> Scope: ...
    def __repr__(self) -> str: ...

class Turn:
    def __init__(self, sender_id: str, content: str) -> None: ...
    def id(self, message_id: str) -> Turn: ...
    def content_type(self, content_type: str) -> Turn: ...
    def at(self, timestamp: datetime.datetime) -> Turn: ...
    def addressed_to(self, recipients: list[str]) -> Turn: ...
    def metadata(self, key: str, value: Any) -> Turn: ...
    def attach(self, source: IngestSource) -> Turn: ...
    def attachments(self, sources: list[IngestSource]) -> Turn: ...
    def __repr__(self) -> str: ...

class AssumeBuilder:
    def then_query(self, query: str) -> AssumeBuilder: ...
    def param(self, key: str, value: Any) -> AssumeBuilder: ...
    def run(self) -> Awaitable[list[dict[str, Any]]]: ...
    def run_sync(self) -> list[dict[str, Any]]: ...
    def __repr__(self) -> str: ...

# ── Handles ────────────────────────────────────────────────────────────────

class Data:
    def message(self, message_id: str) -> Awaitable[MessageView | None]: ...
    def message_sync(self, message_id: str) -> MessageView | None: ...
    def artifact(self, artifact_id: str) -> Awaitable[ArtifactView | None]: ...
    def artifact_sync(self, artifact_id: str) -> ArtifactView | None: ...
    def artifact_bytes(self, artifact_id: str) -> Awaitable[bytes | None]: ...
    def artifact_bytes_sync(self, artifact_id: str) -> bytes | None: ...
    def __repr__(self) -> str: ...

class Goals:
    # Reads.
    def all(self) -> Awaitable[list[GoalView]]: ...
    def all_sync(self) -> list[GoalView]: ...
    def in_phase(self, phase: str) -> Awaitable[list[GoalView]]: ...
    def in_phase_sync(self, phase: str) -> list[GoalView]: ...
    def active(self) -> Awaitable[list[GoalView]]: ...
    def active_sync(self) -> list[GoalView]: ...
    def planned(self) -> Awaitable[list[GoalView]]: ...
    def planned_sync(self) -> list[GoalView]: ...
    def completed(self) -> Awaitable[list[GoalView]]: ...
    def completed_sync(self) -> list[GoalView]: ...
    def get(self, goal_id: str) -> Awaitable[GoalView | None]: ...
    def get_sync(self, goal_id: str) -> GoalView | None: ...
    def tasks(self) -> Awaitable[list[TaskView]]: ...
    def tasks_sync(self) -> list[TaskView]: ...
    def tasks_in(self, phase: str) -> Awaitable[list[TaskView]]: ...
    def tasks_in_sync(self, phase: str) -> list[TaskView]: ...
    def tasks_of(self, goal_id: str) -> Awaitable[list[TaskView]]: ...
    def tasks_of_sync(self, goal_id: str) -> list[TaskView]: ...
    def context(self, goal_id: str) -> Awaitable[GoalContext | None]: ...
    def context_sync(self, goal_id: str) -> GoalContext | None: ...
    # Transitions.
    def start(self, goal_id: str) -> Awaitable[bool]: ...
    def start_sync(self, goal_id: str) -> bool: ...
    def abandon(self, goal_id: str) -> Awaitable[bool]: ...
    def abandon_sync(self, goal_id: str) -> bool: ...
    def set_status(self, goal_id: str, status: str) -> Awaitable[bool]: ...
    def set_status_sync(self, goal_id: str, status: str) -> bool: ...
    def complete(self, goal_id: str, result: Any | None = ...) -> Awaitable[bool]: ...
    def complete_sync(self, goal_id: str, result: Any | None = ...) -> bool: ...
    def start_task(self, task_id: str) -> Awaitable[bool]: ...
    def start_task_sync(self, task_id: str) -> bool: ...
    def block_task(self, task_id: str) -> Awaitable[bool]: ...
    def block_task_sync(self, task_id: str) -> bool: ...
    def complete_task(self, task_id: str) -> Awaitable[bool]: ...
    def complete_task_sync(self, task_id: str) -> bool: ...
    def set_task_status(self, task_id: str, status: str) -> Awaitable[bool]: ...
    def set_task_status_sync(self, task_id: str, status: str) -> bool: ...
    # Creation (keyword-only after `title`).
    def create(
        self,
        title: str,
        *,
        goal_id: str | None = ...,
        description: str | None = ...,
        status: str | None = ...,
        metrics: Any | None = ...,
        guardrails: Any | None = ...,
        deadline: datetime.datetime | None = ...,
        parent_goal_id: str | None = ...,
    ) -> Awaitable[int]: ...
    def create_sync(
        self,
        title: str,
        *,
        goal_id: str | None = ...,
        description: str | None = ...,
        status: str | None = ...,
        metrics: Any | None = ...,
        guardrails: Any | None = ...,
        deadline: datetime.datetime | None = ...,
        parent_goal_id: str | None = ...,
    ) -> int: ...
    def create_task(
        self,
        title: str,
        *,
        task_id: str | None = ...,
        description: str | None = ...,
        status: str | None = ...,
        priority: float | None = ...,
        goal_id: str | None = ...,
        depends_on_task_id: str | None = ...,
        subtask_of_task_id: str | None = ...,
    ) -> Awaitable[int]: ...
    def create_task_sync(
        self,
        title: str,
        *,
        task_id: str | None = ...,
        description: str | None = ...,
        status: str | None = ...,
        priority: float | None = ...,
        goal_id: str | None = ...,
        depends_on_task_id: str | None = ...,
        subtask_of_task_id: str | None = ...,
    ) -> int: ...
    def __repr__(self) -> str: ...

class Session:
    @property
    def session_id(self) -> str: ...
    def observe(self, turn: Turn) -> Awaitable[ObserveResult]: ...
    def observe_sync(self, turn: Turn) -> ObserveResult: ...
    def ingest(self, source: IngestSource) -> Awaitable[IngestOutcome]: ...
    def ingest_sync(self, source: IngestSource) -> IngestOutcome: ...
    def submit(self, turn: Turn) -> Awaitable[None]: ...
    def submit_sync(self, turn: Turn) -> None: ...
    def submit_source(self, source: IngestSource) -> Awaitable[None]: ...
    def submit_source_sync(self, source: IngestSource) -> None: ...
    def flush(self) -> Awaitable[None]: ...
    def flush_sync(self) -> None: ...
    def finalize(self) -> Awaitable[FinalizeReport]: ...
    def finalize_sync(self) -> FinalizeReport: ...
    async def __aenter__(self) -> Session: ...
    async def __aexit__(self, exc_type: object, exc: object, tb: object) -> bool: ...
    def __enter__(self) -> Session: ...
    def __exit__(self, exc_type: object, exc: object, tb: object) -> bool: ...
    def summarize(self) -> Awaitable[int | None]: ...
    def summarize_sync(self) -> int | None: ...
    def forget_turn(self, message_id: str) -> Awaitable[DeletionReport]: ...
    def forget_turn_sync(self, message_id: str) -> DeletionReport: ...
    def delete_turn(self, message_id: str) -> Awaitable[DeletionReport]: ...
    def delete_turn_sync(self, message_id: str) -> DeletionReport: ...
    def delete_document(self, artifact_id: str) -> Awaitable[DeletionReport]: ...
    def delete_document_sync(self, artifact_id: str) -> DeletionReport: ...
    def __repr__(self) -> str: ...

class Agent:
    @property
    def agent_id(self) -> str: ...
    def recall(self, query: str) -> Awaitable[ContextBundle]: ...
    def recall_sync(self, query: str) -> ContextBundle: ...
    def answer(self, question: str) -> Awaitable[Answer]: ...
    def answer_sync(self, question: str) -> Answer: ...
    def query(self, cypher: str) -> Awaitable[list[dict[str, Any]]]: ...
    def query_sync(self, cypher: str) -> list[dict[str, Any]]: ...
    def recall_in(self, query: str, scope: Scope) -> Awaitable[ContextBundle]: ...
    def recall_in_sync(self, query: str, scope: Scope) -> ContextBundle: ...
    def answer_in(self, question: str, scope: Scope) -> Awaitable[Answer]: ...
    def answer_in_sync(self, question: str, scope: Scope) -> Answer: ...
    def query_in(
        self, cypher: str, scope: Scope
    ) -> Awaitable[list[dict[str, Any]]]: ...
    def query_in_sync(self, cypher: str, scope: Scope) -> list[dict[str, Any]]: ...
    def define_rule(self, name: str, source: str) -> Awaitable[int]: ...
    def define_rule_sync(self, name: str, source: str) -> int: ...
    def run_rule(
        self, name: str, return_cols: list[str], params: dict[str, Any] | None = ...
    ) -> Awaitable[list[dict[str, Any]]]: ...
    def run_rule_sync(
        self, name: str, return_cols: list[str], params: dict[str, Any] | None = ...
    ) -> list[dict[str, Any]]: ...
    def abduce(
        self, program: str, params: dict[str, Any] | None = ...
    ) -> Awaitable[AbductionResult]: ...
    def abduce_sync(
        self, program: str, params: dict[str, Any] | None = ...
    ) -> AbductionResult: ...
    def assume(self, assume_block: str) -> AssumeBuilder: ...
    def session(self, session_id: str) -> Session: ...
    @property
    def data(self) -> Data: ...
    @property
    def goals(self) -> Goals: ...
    def delete_session(self, session_id: str) -> Awaitable[DeletionReport]: ...
    def delete_session_sync(self, session_id: str) -> DeletionReport: ...
    def finalize_session(self, session_id: str) -> Awaitable[FinalizeReport]: ...
    def finalize_session_sync(self, session_id: str) -> FinalizeReport: ...
    def consolidate(self) -> Awaitable[CycleStats]: ...
    def consolidate_sync(self) -> CycleStats: ...
    def unfinalized_session_ids(self) -> Awaitable[list[str]]: ...
    def unfinalized_session_ids_sync(self) -> list[str]: ...
    def forget_participant(self, participant_id: str) -> Awaitable[DeletionReport]: ...
    def forget_participant_sync(self, participant_id: str) -> DeletionReport: ...
    def __repr__(self) -> str: ...

class UnikoBuilder:
    def path(self, path: str) -> UnikoBuilder: ...
    def in_memory(self) -> UnikoBuilder: ...
    def llm(self, spec: LlmSpec) -> UnikoBuilder: ...
    def streaming(self, on: bool) -> UnikoBuilder: ...
    def scope_to_agent(self) -> UnikoBuilder: ...
    def build(self) -> Awaitable[Uniko]: ...
    def build_sync(self) -> Uniko: ...
    def __repr__(self) -> str: ...

class Uniko:
    @staticmethod
    def open(path: str) -> Awaitable[Uniko]: ...
    @staticmethod
    def open_sync(path: str) -> Uniko: ...
    @staticmethod
    def in_memory() -> Awaitable[Uniko]: ...
    @staticmethod
    def in_memory_sync() -> Uniko: ...
    @staticmethod
    def builder() -> UnikoBuilder: ...
    def agent(self, agent_id: str) -> Agent: ...
    def config(self) -> dict[str, Any]: ...
    def purge(self) -> Awaitable[DeletionReport]: ...
    def purge_sync(self) -> DeletionReport: ...
    def shutdown(self) -> Awaitable[None]: ...
    def shutdown_sync(self) -> None: ...
    def __repr__(self) -> str: ...

__all__ = [
    "Uniko",
    "UnikoBuilder",
    "LlmSpec",
    "Agent",
    "Session",
    "Turn",
    "Data",
    "Goals",
    "IngestSource",
    "Scope",
    "AssumeBuilder",
    "RecallSource",
    "RecallItem",
    "ContextBundle",
    "Answer",
    "ObserveResult",
    "DeletionReport",
    "MessageView",
    "ArtifactView",
    "GoalView",
    "TaskView",
    "GoalContext",
    "IngestOutcome",
    "AbductionResult",
    "UnikoError",
    "ConfigError",
    "LlmError",
    "TimeoutError",
    "ConflictError",
    "UnsupportedError",
]
